// @ts-check

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import mdx from "@astrojs/mdx";
import sitemap from "@astrojs/sitemap";
import { defineConfig, fontProviders } from "astro/config";

import tailwindcss from "@tailwindcss/vite";

// Migrated WordPress URLs that need to redirect to their new /blog/<slug>/ form.
// Generated by scripts/migrate.mjs and tracked in version control.
const redirectsPath = fileURLToPath(
  new URL("./astro-redirects.generated.json", import.meta.url),
);
const generatedRedirects = JSON.parse(readFileSync(redirectsPath, "utf8"));

// Manual redirects layered on top of the generated ones (URL renames decided post-migration).
const manualRedirects = {
  "/about-me": "/about",
};

const redirects = { ...generatedRedirects, ...manualRedirects };

// https://astro.build/config
export default defineConfig({
  site: "https://tomdehnel.com",
  trailingSlash: "ignore",
  redirects,
  integrations: [mdx(), sitemap()],

  fonts: [
    {
      provider: fontProviders.local(),
      name: "Atkinson",
      cssVariable: "--font-atkinson",
      fallbacks: ["sans-serif"],
      options: {
        variants: [
          {
            src: ["./src/assets/fonts/atkinson-regular.woff"],
            weight: 400,
            style: "normal",
            display: "swap",
          },
          {
            src: ["./src/assets/fonts/atkinson-bold.woff"],
            weight: 700,
            style: "normal",
            display: "swap",
          },
        ],
      },
    },
  ],

  vite: {
    plugins: [tailwindcss()],
  },
});
