// @ts-check

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import mdx from "@astrojs/mdx";
import sitemap from "@astrojs/sitemap";
import { defineConfig, fontProviders } from "astro/config";

import tailwindcss from "@tailwindcss/vite";

// Migrated WordPress URLs that need to redirect to their new /blog/<slug>/ form.
// Generated by scripts/migrate.mjs and tracked in version control.
const redirectsPath = fileURLToPath(
  new URL("./astro-redirects.generated.json", import.meta.url),
);
const generatedRedirects = JSON.parse(readFileSync(redirectsPath, "utf8"));

// Manual redirects layered on top of the generated ones (URL renames decided post-migration).
const manualRedirects = {
  "/about-me": "/about",
};

const redirects = { ...generatedRedirects, ...manualRedirects };

/**
 * Tiny rehype plugin: mark every <img> inside Markdown bodies as lazy-loaded
 * with async decoding. Hero images are rendered by BlogPost.astro / PageLayout.astro
 * and aren't affected — those stay eager and high-priority.
 */
function rehypeLazyImages() {
  return (tree) => {
    const visit = (node) => {
      if (node.type === "element" && node.tagName === "img") {
        node.properties = node.properties || {};
        if (!("loading" in node.properties)) node.properties.loading = "lazy";
        if (!("decoding" in node.properties)) node.properties.decoding = "async";
      }
      if (node.children) for (const c of node.children) visit(c);
    };
    visit(tree);
  };
}

// https://astro.build/config
export default defineConfig({
  site: "https://tomdehnel.com",
  trailingSlash: "ignore",
  redirects,
  integrations: [mdx(), sitemap()],

  markdown: {
    rehypePlugins: [rehypeLazyImages],
  },

  fonts: [
    {
      provider: fontProviders.local(),
      name: "Atkinson",
      cssVariable: "--font-atkinson",
      fallbacks: ["sans-serif"],
      options: {
        variants: [
          {
            src: ["./src/assets/fonts/atkinson-regular.woff"],
            weight: 400,
            style: "normal",
            display: "swap",
          },
          {
            src: ["./src/assets/fonts/atkinson-bold.woff"],
            weight: 700,
            style: "normal",
            display: "swap",
          },
        ],
      },
    },
  ],

  vite: {
    plugins: [tailwindcss()],
  },
});
